// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Reading struct {
	ID           int64   `json:"id"`
	TimeUnixMs   int64   `json:"time_unix_ms"`
	Value        float64 `json:"value"`
	Display      float64 `json:"display"`
	Unit         string  `json:"unit"`
	RangeLow     int64   `json:"range_low"`
	RangeHigh    int64   `json:"range_high"`
	Overload     string  `json:"overload"`
	MaxMin       string  `json:"max_min"`
	LowPower     int64   `json:"low_power"`
	AutoPowerOff int64   `json:"auto_power_off"`
	Backlight    int64   `json:"backlight"`
	Hold         int64   `json:"hold"`
}
