// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getDashboardConfig = `-- name: GetDashboardConfig :one
SELECT ideal_max, unsafe_min, chart_min, chart_max
FROM dashboard_config
WHERE id = 1
`

type GetDashboardConfigRow struct {
	IdealMax  float64 `json:"ideal_max"`
	UnsafeMin float64 `json:"unsafe_min"`
	ChartMin  float64 `json:"chart_min"`
	ChartMax  float64 `json:"chart_max"`
}

func (q *Queries) GetDashboardConfig(ctx context.Context) (GetDashboardConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardConfig)
	var i GetDashboardConfigRow
	err := row.Scan(
		&i.IdealMax,
		&i.UnsafeMin,
		&i.ChartMin,
		&i.ChartMax,
	)
	return i, err
}

const insertReading = `-- name: InsertReading :exec
INSERT INTO readings (
  time_unix_ms, value, display, unit, range_low, range_high, overload, max_min,
  low_power, auto_power_off, backlight, hold
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReadingParams struct {
	TimeUnixMs   int64   `json:"time_unix_ms"`
	Value        float64 `json:"value"`
	Display      float64 `json:"display"`
	Unit         string  `json:"unit"`
	RangeLow     int64   `json:"range_low"`
	RangeHigh    int64   `json:"range_high"`
	Overload     string  `json:"overload"`
	MaxMin       string  `json:"max_min"`
	LowPower     int64   `json:"low_power"`
	AutoPowerOff int64   `json:"auto_power_off"`
	Backlight    int64   `json:"backlight"`
	Hold         int64   `json:"hold"`
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) error {
	_, err := q.db.ExecContext(ctx, insertReading,
		arg.TimeUnixMs,
		arg.Value,
		arg.Display,
		arg.Unit,
		arg.RangeLow,
		arg.RangeHigh,
		arg.Overload,
		arg.MaxMin,
		arg.LowPower,
		arg.AutoPowerOff,
		arg.Backlight,
		arg.Hold,
	)
	return err
}

const listRecentReadings = `-- name: ListRecentReadings :many
SELECT time_unix_ms, value, display, unit, range_low, range_high, overload, max_min,
       low_power, auto_power_off, backlight, hold
FROM readings
WHERE time_unix_ms >= ?
ORDER BY time_unix_ms DESC
LIMIT ?
`

type ListRecentReadingsParams struct {
	TimeUnixMs int64 `json:"time_unix_ms"`
	Limit      int64 `json:"limit"`
}

type ListRecentReadingsRow struct {
	TimeUnixMs   int64   `json:"time_unix_ms"`
	Value        float64 `json:"value"`
	Display      float64 `json:"display"`
	Unit         string  `json:"unit"`
	RangeLow     int64   `json:"range_low"`
	RangeHigh    int64   `json:"range_high"`
	Overload     string  `json:"overload"`
	MaxMin       string  `json:"max_min"`
	LowPower     int64   `json:"low_power"`
	AutoPowerOff int64   `json:"auto_power_off"`
	Backlight    int64   `json:"backlight"`
	Hold         int64   `json:"hold"`
}

func (q *Queries) ListRecentReadings(ctx context.Context, arg ListRecentReadingsParams) ([]ListRecentReadingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentReadings, arg.TimeUnixMs, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentReadingsRow{}
	for rows.Next() {
		var i ListRecentReadingsRow
		if err := rows.Scan(
			&i.TimeUnixMs,
			&i.Value,
			&i.Display,
			&i.Unit,
			&i.RangeLow,
			&i.RangeHigh,
			&i.Overload,
			&i.MaxMin,
			&i.LowPower,
			&i.AutoPowerOff,
			&i.Backlight,
			&i.Hold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDashboardConfig = `-- name: UpsertDashboardConfig :exec
INSERT INTO dashboard_config (
  id, ideal_max, unsafe_min, chart_min, chart_max, updated_unix_ms
) VALUES (1, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  ideal_max = excluded.ideal_max,
  unsafe_min = excluded.unsafe_min,
  chart_min = excluded.chart_min,
  chart_max = excluded.chart_max,
  updated_unix_ms = excluded.updated_unix_ms
`

type UpsertDashboardConfigParams struct {
	IdealMax      float64 `json:"ideal_max"`
	UnsafeMin     float64 `json:"unsafe_min"`
	ChartMin      float64 `json:"chart_min"`
	ChartMax      float64 `json:"chart_max"`
	UpdatedUnixMs int64   `json:"updated_unix_ms"`
}

func (q *Queries) UpsertDashboardConfig(ctx context.Context, arg UpsertDashboardConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertDashboardConfig,
		arg.IdealMax,
		arg.UnsafeMin,
		arg.ChartMin,
		arg.ChartMax,
		arg.UpdatedUnixMs,
	)
	return err
}
