// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line dashboard.gsx:5:1
func DashboardPage() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line dashboard.gsx:6:2
		_gsxgw.S("<html lang=\"en\">")
//line dashboard.gsx:7:3
		_gsxgw.S("<head>")
//line dashboard.gsx:8:4
		_gsxgw.S("<meta charset=\"utf-8\">")
//line dashboard.gsx:9:4
		_gsxgw.S("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
//line dashboard.gsx:10:4
		_gsxgw.S("<title>Sound Level</title>")
//line dashboard.gsx:11:4
		_gsxgw.S("<style")
		_gsxgw.Nonce(ctx)
		_gsxgw.S(">")
		_gsxgw.S(string(gsx.RawCSS(DashboardCSS)))
		_gsxgw.S("</style></head>")
//line dashboard.gsx:13:3
		_gsxgw.S("<body>")
//line dashboard.gsx:14:4
		_gsxgw.S("<main class=\"app\">")
//line dashboard.gsx:15:5
		_gsxgw.NodeResult(_gsxrenderTopSection(ctx, _gsxgw))
//line dashboard.gsx:16:5
		_gsxgw.NodeResult(_gsxrenderChartPanel(ctx, _gsxgw))
		_gsxgw.S("</main>")
//line dashboard.gsx:18:4
		_gsxgw.S("<script")
		_gsxgw.Nonce(ctx)
		_gsxgw.S(">")
		_gsxgw.JSVal(gsx.RawJS(DashboardJS))
		_gsxgw.S("</script></body></html>")
		return _gsxgw.Err()
	})
}

//line dashboard.gsx:23:1
func TopSection() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderTopSection(ctx, _gsxgw)
	})
}

func _gsxrenderTopSection(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line dashboard.gsx:24:2
	_gsxgw.S("<section class=\"top\">")
//line dashboard.gsx:25:3
	_gsxgw.NodeResult(_gsxrenderReadingPanel(ctx, _gsxgw))
//line dashboard.gsx:26:3
	_gsxgw.NodeResult(_gsxrenderSidePanel(ctx, _gsxgw))
	_gsxgw.S("</section>")
	return _gsxgw.Err()
}

//line dashboard.gsx:30:1
func ReadingPanel() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderReadingPanel(ctx, _gsxgw)
	})
}

func _gsxrenderReadingPanel(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line dashboard.gsx:31:2
	_gsxgw.S("<div class=\"reading\">")
//line dashboard.gsx:32:3
	_gsxgw.S("<div class=\"value\" id=\"value\">--.-</div>")
//line dashboard.gsx:33:3
	_gsxgw.S("<div class=\"unit\" id=\"unit\">dBA</div>")
//line dashboard.gsx:34:3
	_gsxgw.S("<div class=\"band\" id=\"band\">Waiting</div></div>")
	return _gsxgw.Err()
}

//line dashboard.gsx:38:1
func SidePanel() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderSidePanel(ctx, _gsxgw)
	})
}

func _gsxrenderSidePanel(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line dashboard.gsx:39:2
	_gsxgw.S("<aside class=\"side\">")
//line dashboard.gsx:40:3
	_gsxgw.S("<div class=\"stats\">")
//line dashboard.gsx:41:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Peak", "peak", "--.-", false))
//line dashboard.gsx:42:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Average", "avg", "--.-", false))
//line dashboard.gsx:43:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Window", "window", "--", true))
//line dashboard.gsx:44:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Session", "session", "--", true))
//line dashboard.gsx:45:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Battery", "battery", "--", true))
//line dashboard.gsx:46:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Auto-Off", "autoOff", "--", true))
//line dashboard.gsx:47:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Range", "range", "--", true))
//line dashboard.gsx:48:4
	_gsxgw.NodeResult(_gsxrenderStatTile(ctx, _gsxgw, "Meter", "meterState", "--", true))
//line dashboard.gsx:49:4
	_gsxgw.NodeResult(_gsxrenderStatusTile(ctx, _gsxgw))
	_gsxgw.S("</div></aside>")
	return _gsxgw.Err()
}

//line dashboard.gsx:54:1
func StatTile(label string, id string, value string, small bool) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderStatTile(ctx, _gsxgw, label, id, value, small)
	})
}

func _gsxrenderStatTile(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, label string, id string, value string, small bool) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line dashboard.gsx:55:2
	_gsxgw.S("<div>")
//line dashboard.gsx:56:3
	_gsxgw.S("<div class=\"label\">")
//line dashboard.gsx:56:22
	_gsxgw.Text(string(label))
	_gsxgw.S("</div>")
//line dashboard.gsx:57:3
	_gsxgw.S("<div id=\"")
	_gsxgw.AttrValue(string(id))
	_gsxgw.S("\" class=\"")
	_gsxgw.Class(_gsxrt.DefaultClassMerge, _gsxrt.Class("metric"), _gsxrt.ClassIf("small", small))
	_gsxgw.S("\">")
//line dashboard.gsx:57:51
	_gsxgw.Text(string(value))
	_gsxgw.S("</div></div>")
	return _gsxgw.Err()
}

//line dashboard.gsx:61:1
func StatusTile() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderStatusTile(ctx, _gsxgw)
	})
}

func _gsxrenderStatusTile(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line dashboard.gsx:62:2
	_gsxgw.S("<div class=\"statusTile\">")
//line dashboard.gsx:63:3
	_gsxgw.S("<div class=\"label\">Status</div>")
//line dashboard.gsx:64:3
	_gsxgw.S("<div class=\"metric small status\">")
//line dashboard.gsx:65:4
	_gsxgw.S("<span class=\"dot\" id=\"dot\"></span>")
//line dashboard.gsx:66:4
	_gsxgw.S("<span id=\"status\">starting</span></div></div>")
	return _gsxgw.Err()
}

//line dashboard.gsx:71:1
func ChartPanel() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderChartPanel(ctx, _gsxgw)
	})
}

func _gsxrenderChartPanel(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line dashboard.gsx:72:2
	_gsxgw.S("<section class=\"chartShell\">")
//line dashboard.gsx:73:3
	_gsxgw.S("<canvas id=\"chart\"></canvas></section>")
	return _gsxgw.Err()
}
